name = "RiccatiRecursion"
uuid = "f80364bd-80b2-4659-b6ab-c8328802dfcf"
authors = ["Ian McInerney <ian.mcinerney@manchester.ac.uk> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
